### ISSUE TITLE
Server implementation

### ISSUE THREAD

**Issue by bennaux** [raphaelm/python-fints#102]
Hey everyone, is there, anywhere out there, a free/OS implementation of the server side of the FinTS process? 

I regularly have to use banking accounts that do not have FinTS access and have to have my small WebScrapers export their data to files and import those files manually into my accounting program. That process would be so much easier if I could connect my web scrapers to a locally running FinTS server (talking to the web scrapers) and have the accounting program talk to it.

**Comment by raphaelm** [comment]
> Hey everyone, is there, anywhere out there, a free/OS implementation of the server side of the FinTS process?

Never heard of one, and I'd be pretty surprised if someone went through all that trouble. :( I only know about [very expensive ones](https://subsembly.com/download/Subsembly.Preisliste.pdf).

**Comment by jHetzer** [comment]
Since 4 years not maintained but i think it should work:
[Open-Fin-TS-JS-Client](https://www.npmjs.com/package/open-fin-ts-js-client)
```
mkdir FinTS
cd FinTS
git clone https://github.com/jschyma/open_fints_js_client
cd open_fints_js_client/
npm install
node dev/Run_FinTSServer.js
```
you would need to implement a connection between our web scrappers and the test server implementation

**Comment by valb3r** [comment]
Hi all, there is one OpenSource HBCI/FinTS sandbox. I'm the contributor of the OpenBanking gateway (https://github.com/adorsys/open-banking-gateway) and we have implemented HBCI Sandbox server here: 
https://github.com/adorsys/open-banking-gateway/tree/develop/opba-protocols/sandboxes/hbci-sandbox/src/main/java/de/adorsys/opba/protocol/sandbox/hbci

It supports account, transaction listings, payments with SCA. So if there any interest, I can explain things and maybe we could cooperate - you would use our Sandbox and we would have more testers :)

**Comment by raphaelm** [comment]
Amazing, glad to know you developed this! Would be very interesting to use it for testing of this library. I don't  have the time to look into it deeper right now, though.

**Comment by valb3r** [comment]
@raphaelm Sure, have a look when you have time. FYI we have released Docker image with server
```
docker run -p 8090:8090 adorsys/open-banking-gateway-hbci-sandbox-server:0.19.1
```
and HBCI endpoint will be available at `http://localhost:8090/hbci-mock`
Known issues: Wrong sequence numbers sometimes occur
