### ISSUE TITLE
Dialog error when requesting account balance from fiducia (Raiffeisen-Volksbank)

### ISSUE THREAD

**Issue by mic-e** [raphaelm/python-fints#11]
When attempting to request an acocunt balance for my account I get `error 9050: Die Nachricht enthält fehler.`

This minimum example reproduces the issue:

```python
import fints
import fints.client

print(fints.version)

f = fints.client.FinTS3PinTanClient(
    account, user, pin,
    'https://hbci11.fiducia.de/cgi-bin/hbciservlet'
)

for account in f.get_sepa_accounts():
    print(f.get_holdings(account))

```

Which will produce the output:

```
mic@mic ~ $ python3 minex.py 
0.2.1
Traceback (most recent call last):
  File "minex.py", line 16, in <module>
    print(f.get_holdings(account))
  File "/usr/lib/python3.6/site-packages/fints/client.py", line 177, in get_holdings
    resp = dialog.send(msg)
  File "/usr/lib/python3.6/site-packages/fints/dialog.py", line 99, in send
    raise FinTSDialogError(resp.get_summary_by_segment('HIRMG'))
fints.dialog.FinTSDialogError: {'9050': 'Die Nachricht enthält Fehler.'}
```
The `get_sepa_accounts` and `get_statement` functions work just fine.

I'd be happy to assist, but I'd rather not divulge my account details here... unfortunately the debug logs contain my PIN.

**Comment by raphaelm** [comment]
get_holdings does not request account balance but stock property (aktien), maybe this is just not enabled on your account? You can try get_balance instead

**Comment by mic-e** [comment]
Thank you very much, `get_balance` works perfectly fine. You can add Raiffeisen-Volksbank to your list of tested banks.

Anyways, IMO FinTS is pretty broken if "Dialog error" is the error message that you get when you request stocks on an account where it's not enabled.
