### ISSUE TITLE
Error when TAN input is requested for get_xml_transactions 

### ISSUE THREAD

**Issue by forgeorge** [raphaelm/python-fints#111]
Hello Raphael and team, 
thanks for this great library!

The Stadtsparkasse München requires a TAN for transactions older than 90 days.
When trying to run get_transactions_xml for a longer period, an error occurs:

        File ...\client.py, line 583, in get_transactions_xml
        for seg in responses:
        TypeError: 'NeedTANResponse' object is not iterable

FinTS URL: 'https://banking-by6.s-fints-pt-by.de/fints30'

Checking wether responses is iterable solved the problem:
        from collections.abc import Iterable
        .....
        if isinstance(responses, Iterable):
            for seg in responses:
                booked_streams.extend(seg.statement_booked.camt_statements)
                pending_streams.append(seg.statement_pending)
            return booked_streams, pending_streams
        else:
            return responses

**Comment by raphaelm** [comment]
Can you check if the PR in #110 fixes this for you as well? If so, I'm gonna go ahead and merge it.

**Comment by forgeorge** [comment]
Yes, PR #110 fixes the problem. Thanks for looking into this topic.

**Comment by robng** [comment]
Hello! I am getting the same error (it appears the change from #110 came after version 3.0.0 which is the latest version available via pip). However being new to Python, I'm wondering if there is a way to include this repository as a dependency directly? It seems that `pip install -e git+git://github.com/raphaelm/python-fints` is meant to do just yet, but I am unsure what the `#egg=` parameter should be... 

Maybe someone can help?

Thanks guys!
