### ISSUE TITLE
Feature Request: Sammler

### ISSUE THREAD

**Issue by ski7777** [raphaelm/python-fints#112]
Hello,

I would like to create so called Sammler. Sadly I don't know where in the code I should implement it. It would be great to get some hints so I can implement it.

Raphael

**Comment by raphaelm** [comment]
How is that different from the operations we already support?

**Comment by ski7777** [comment]
A Sammler can either be used to make a Lastschrift or multiple transfers at once. Therefore you have to fill in all the required data for each transaction (can be added, deleted and edited at any time) and then you start the transaction with only one TAN.

**Comment by raphaelm** [comment]
You can totally do that with the transfers and debits we support.
