### ISSUE TITLE
Feature Request: Transfer

### ISSUE THREAD

**Issue by ski7777** [raphaelm/python-fints#113]
Hello,

I would like to transfer money between back accounts (Umbuchung). Sadly I don't know where in the code I should implement it. It would be great to get some hints so I can implement it.

Raphael

**Comment by raphaelm** [comment]
Is that different to a transfer to a separate account (which is implemented)? There seems to be a legacy operation "HKUMB" but it does not seem to be used any more.

**Comment by ski7777** [comment]
Sadly I cant check on that or is there any way to MITM the Sparkasse App?

**Comment by raphaelm** [comment]
We'll, you can try using the library to make a transfer to your own account and see if it has the same result.
