### ISSUE TITLE
Is it possible to persist and restore a previous session for daily invocations?

### ISSUE THREAD

**Issue by bojanjanisch** [raphaelm/python-fints#115]
I've connected sucessfully manually to my Deutsche Bank account which requires photoTAN authentication using my mobile phone. However I want a daily output of my transactions without re-authorizing each day the access. 

Is there a way to cache the session or keep the dialog open for multiple days / weeks without re-authenticating each request?

**Comment by raphaelm** [comment]
Our library provides everything that you need to do this:
https://python-fints.readthedocs.io/en/latest/client.html#storing-and-restoring-dialog-state

**BUT** as far as I know no bank will allow you to keep a session open this long and will just log you out server-side after a specific timeframe.
