### ISSUE TITLE
Fetching account balances from specific dates (ranges)?

### ISSUE THREAD

**Issue by bojanjanisch** [raphaelm/python-fints#116]
**Describe the bug**
Refering the documentation of mt940 Models (https://mt940.readthedocs.io/en/latest/mt940.html#mt940.models.Balance) the balance can be requested for specific dates. The get_balance-Method returns only the current balance. I'd like to request a change and make the date selection optionable in the get_balance-Method.

**Bank I tested this with*
Name of the bank:
FinTS URL:

**Expected behavior**
Return the booked_balance of a given date. Return the current booked_balance if Date is None.

**Code required to reproduce**
```
import datetime
...
f = FinTS3Client(...)
...
with f:
    f.get_balance(account, datetime.date(2020, 7, 22))
```

**Log output / error message**

**Additional context**
I couldn't find a change request button since this is not really a bug, just a missing functionality.

**Comment by raphaelm** [comment]
The mt940 indeed has a data property to store the date of a balance, but that doesn't mean that FinTS has an API to query the result for a specific date ;) I checked, and I can't see a FinTS API call that would allow this. HKSAL always returns the current balance.

**Comment by bojanjanisch** [comment]
Well considering the current fints 3.0 documentation of ZKA (https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Messages_Geschaeftsvorfaelle_2015-08-07_final_version.pdf) under section B.4 it should be possible. 

How did you check that the call wouldn't allow this?

**Comment by raphaelm** [comment]
B.4 describes a data type that is used by the bank in their **response**. It says "when the bank sends you a balance, it also tells you the date of that balance". E.g. if you fetch the "current balance" on a sunday, it might have the date of the previous friday.

The API request is documented in that document in section C.2.1.2.1 (a) and has no parameter to specify a date **to** the bank

**Comment by bojanjanisch** [comment]
Well that's a bit disappointing. So is there another approach to get something like a statement of account?
