### ISSUE TITLE
Error when calling minimal_interactive_cli_bootstrap

### ISSUE THREAD

**Issue by testalucida** [raphaelm/python-fints#118]
Hello,
to access my DKB banking account I'm initializing FinTS3PinTanClient like so:

```
   client_args = (
       '12030000',  # BLZ
       'xxxxxxx',  # USER
       getpass.getpass('PIN: '),
       'https://banking-dkb.s-fints-pt-dkb.de/fints30'  # ENDPOINT
   )

   f = FinTS3PinTanClient(*client_args)
```

The subsequent call to 

`minimal_interactive_cli_bootstrap(f)`

raises the error:
> .../fints/client.py", line 1284, in _process_response
>     raise FinTSClientError("Error during dialog initialization, could not fetch BPD. Please check that you "
> fints.exceptions.FinTSClientError: Error during dialog initialization, could not fetch BPD. Please check that you passed the correct bank identifier to the HBCI URL of the correct bank.

Does anybody see what's wrong with my code?

Thanks in advance

**Comment by raphaelm** [comment]
It's probably not you, see #106

**Comment by testalucida** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-size:14px;font-family:verdana, geneva, sans-serif;;}thank you 
 
Raphael Michel wrote on 06.10.2020 09:06 (GMT +02:00):

It's probably not you, see #106
