### ISSUE TITLE
PyPi formatting issue

### ISSUE THREAD

**Issue by tbm** [raphaelm/python-fints#119]
https://pypi.org/project/fints/ displays Markdown code inline instead of a proper HTML link.

> \[Read our documentation for more info\](https://python-fints.readthedocs.io)

**Comment by lukasjuhrich** [comment]
If I understand [`pip`s documentation](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#creating-a-readme-file) correctly,  all that's needed is to set `long_description_content_type='text/markdown'` in the `setup` method:
https://github.com/raphaelm/python-fints/blob/846c25f5f6ae578cde5151fc30b5f7a3601a95ac/setup.py#L16-L20
