### ISSUE TITLE
Mask pins in log output

### ISSUE THREAD

**Issue by chbndrhnns** [raphaelm/python-fints#12]
I suggest to not print the passwords/pins in cleartext in the debug output. Is it possible to mask them?

**Comment by raphaelm** [comment]
Good point. It's probably not trivial, though, as a simple search and replace has its problems: Imagine your password is something like ``HKIDN`` which is a FinTS command. If we now replace all ``HKIDN`` by ``*****``, everybody can still see what your password must be ;)

**Comment by UweZiegenhagen** [comment]
How about a regular expression or embedding the password into a sequence of marker characters like @@@Password@@@?

**Comment by pabra** [comment]
I had to do something similar a while ago.
I got inspiration from here: https://stackoverflow.com/a/2673863
```python
In [38]: class Password(str):
    ...:     def __new__(self, value):
    ...:         self.value = value
    ...:         obj = str.__new__(self, value)
    ...:         return obj
    ...:     
    ...:     def __str__(self):
    ...:         return '***'
    ...:     

In [39]: p = Password('my secret')

In [40]: print(p)
***

In [41]: print(p.value)
my secret
```

**Comment by raphaelm** [comment]
Sorry for the late reply here.

> How about a regular expression

What would the regular expression be? This might work for some cases, yes, but probably not for all.

>  or embedding the password into a sequence of marker characters like @@@password@@@?

Well, then it probably stops working since that is not your password and your bank will not recognize it ;)

> I had to do something similar a while ago.
> I got inspiration from here: https://stackoverflow.com/a/2673863

That's not gonna work, since we don't print the password directly, but the end result inside the HBCI calls.

**Comment by pabra** [comment]
Then just flip the behaviour of the Password class.
```python
In [1]: from contextlib import contextmanager
   ...: 
   ...: # create class that will decide if password should be "visible"
   ...: class PasswordProtector():
   ...:     def __init__(self):
   ...:         self.protected = False
   ...:     
   ...:     @contextmanager
   ...:     def protect(self):
   ...:         try:
   ...:             self.protected = True
   ...:             yield None
   ...:         finally:
   ...:             self.protected = False
   ...: 
   ...: # get instance
   ...: pprotector = PasswordProtector()
   ...: 
   ...: class Password(str):
   ...:     def __init__(self, value):
   ...:         # bind protector instance to each Password instance
   ...:         self.protector = pprotector
   ...:         
   ...:     def __str__(self):
   ...:         # now the protector decides how the stringified Password will look like
   ...:         if self.protector.protected:
   ...:             return '***'
   ...:         
   ...:         return self
   ...:     
   ...:     def __repr__(self):
   ...:         return repr(self.__str__())
   ...:     

In [2]: # regular string
   ...: username = 'myUser'
   ...: # instance of Password
   ...: password = Password('myPass')
   ...: 

In [3]: # use password as string to authenticate
   ...: print('authenticate: {}:{}'.format(username, password))
authenticate: myUser:myPass

In [4]: # create protected context
   ...: with pprotector.protect():
   ...:     # in here the password won't be printable
   ...:     # now write stuff to the log
   ...:     msg = 'We used username {!r} and password {!r} to authenticate.'
   ...:     print(msg.format(username, password))
   ...: 
We used username 'myUser' and password '***' to authenticate.

In [5]: # outside the `with` scope/context, use password as string again
   ...: print('authenticate2: {}:{}'.format(username, password))
authenticate2: myUser:myPass
```

**Comment by raphaelm** [comment]
I don't believe that this will work, but feel free to create a pull request for it.

**Comment by pabra** [comment]
I'm sorry. I should have had a look into your code first.
If I saw it right, you currently create a message, log it, send it and log the response.
Assuming, that the responses don't contain the password again, you could create messages twice. 
Once to send to the bank server. And the second time wrapped `with` password protector as I suggested and used only for logging.
