### ISSUE TITLE
Can't get transactions anymore due to missing system_id

### ISSUE THREAD

**Issue by Jdu278** [raphaelm/python-fints#147]
**Describe the bug**
I am no longer able to fetch transactions from two bank accounts using a script that functioned correctly just last week. The problem started this week, and I haven't made any changes to the script. Can you help me understand what might be causing this?

**Banks I tested this with**
Name of the banks: PSD Bank Braunschweig, GLS Bank
FinTS URLs: [https://hbci11.fiducia.de/cgi-bin/hbciservlet](https://hbci11.fiducia.de/cgi-bin/hbciservlet), [https://hbci11.fiducia.de/cgi-bin/hbciservlet](https://hbci-pintan.gad.de/cgi-bin/hbciservlet)

**Expected behavior**
The script fails with `Could not find system_id`. 

**Code required to reproduce**
```
f = FinTS3PinTanClient(
    os.getenv('BANK_BLZ'),
    os.getenv('LOGIN_NAME'),
    pin,
    os.getenv('BANK_FinTS_URL'),
    product_id=None
)

with f:
    # Since PSD2, a TAN might be needed for dialog initialization. Let's check if there is one required
    if f.init_tan_response:
        print("A TAN is required", f.init_tan_response.challenge)
        tan = input('Please enter TAN:')
        f.send_tan(f.init_tan_response, tan)

    # Fetch accounts
    accounts = f.get_sepa_accounts()
    print(f'Accounts: {accounts}')
```
**Log output / error message**
```
    with f:
  File "pyenv/versions/3.8.10/lib/python3.8/site-packages/fints/client.py", line 250, in __enter__
    self._standing_dialog = self._get_dialog()
  File "pyenv/versions/3.8.10/lib/python3.8/site-packages/fints/client.py", line 273, in _get_dialog
    self._ensure_system_id()
  File "pyenv/versions/3.8.10/lib/python3.8/site-packages/fints/client.py", line 1151, in _ensure_system_id
    raise ValueError('Could not find system_id')
ValueError: Could not find system_id
```

**Comment by raphaelm** [comment]
This could be almost anything, the actual problem is probably hidden somewhere deep in the very verbose debug log :/

I had the same issue with a Postbank account after their recent system migration because they wanted be to log into the web banking first to set up a new 2fa method

**Comment by Jdu278** [comment]
> This could be almost anything, the actual problem is probably hidden somewhere deep in the very verbose debug log :/

Alright, are there any specific entries I should be mindful of, while searching through the log?

**Comment by raphaelm** [comment]
Not really, anything that looks like a human-readable error message :(

**Comment by maweki** [comment]
I have the same issue since a few days with Triodos (they use the same hbci server instance/url).

**Comment by raphaelm** [comment]
Ah, I just had the same problem with a script with Triodos. I believe it is because the product_id bundled with this library has been disabled by the banks. You will need to request your own. Read more:

https://python-fints.readthedocs.io/en/latest/quickstart.html#register-for-a-product-id
https://python-fints.readthedocs.io/en/latest/upgrading_3_4.html
https://www.hbci-zka.de/register/prod_register.htm
