### ISSUE TITLE
VRBank OBB can't connect, ValueError: Could not find system_id

### ISSUE THREAD

**Issue by IgEntICH** [raphaelm/python-fints#149]
**Describe the bug**
I can't connect to the bank, I always get the error message I pasted below. It is the first time I try to connect to the bank with FinTS/HBCI.

**Bank I tested this with*
Name of the bank: Volksbank Raiffeisenbank Oberbayern Südost eG
FinTS URL: https://hbci11.fiducia.de/cgi-bin/hbciservlet

**Expected behavior**
It connects and I can use minimal_interactive_cli_bootstrap().

**Code required to reproduce**
I used the code from https://python-fints.readthedocs.io/en/latest/trouble.html and also added a product_id.

**Log output / error message**
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    minimal_interactive_cli_bootstrap(f)
  File "python3.8/site-packages/fints/utils.py", line 310, in minimal_interactive_cli_bootstrap
    client.fetch_tan_mechanisms()
  File "python3.8/site-packages/fints/client.py", line 1138, in fetch_tan_mechanisms
    self._ensure_system_id()
  File "python3.8/site-packages/fints/client.py", line 1156, in _ensure_system_id
    raise ValueError('Could not find system_id')
ValueError: Could not find system_id
```

**Comment by raphaelm** [comment]
Is the product ID you are using registered and valid?

**Comment by Jan-2k** [comment]
I'm having the same issue. I never registered a product id. I was using the built-in one since my project is only for private purposes and I was not sure if the registration process works for such projects too. Has the support ended now?

**Comment by raphaelm** [comment]
The built-in product ID has been disabled by the banks. Everyone needs to register their own, even for private projects. See also https://python-fints.readthedocs.io/en/latest/upgrading_3_4.html

**Comment by IgEntICH** [comment]
The problem was that the product ID was not yet activated. After messaging the ZKA again it worked without problems.
