### ISSUE TITLE
Warum?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [raphaelm/python-fints#156]
Warum redet ihr auf Englisch über ein Protokoll, das nur für deutsche Banken relevant ist? 

Weil mal einer von 2000 Nutzern nicht Deutsch können könnte und zu faul ist, einen Übersetzer zu verwenden und ihr dem in deutsch-dummdämlichem vorauseilendem Gehorsam in den Arsch kriecht?

Mich interessiert die Antwort nicht und ich werde sie nicht lesen. Meine Aussage war rhethorisch und soll zum Nachdenken und zur Verhaltensänderung beitragen.

**Comment by raphaelm** [comment]
Deine Aussage ist nicht rhetorisch, dein Kommentar ist im Tonfall von vorne bis hinten völlig daneben. Geh weg, nutz andere Software und interagiere bitte nie wieder mit mir.
