### ISSUE TITLE
ImportError: cannot import name '_power_of_two' from 'enum'

### ISSUE THREAD

**Issue by wunder-view** [raphaelm/python-fints#166]
Fresh install. The very basic example, gives:

ImportError: cannot import name '_power_of_two' from 'enum' (/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py)

As far as i could find out, _power_of_two was a private function available in the "enum" lib
It was removed a few month ago: https://github.com/python/cpython/issues/101341

Error comes from the "enum_tools" lib that is in the dependency tree.
Downgrading it works: pip3 install enum-tools==0.11.0

Any chance to resolve that?

**Comment by peteh** [comment]
+1
