### ISSUE TITLE
Troubleshooting Script does not pay Attention to non-optional param "product_id"

### ISSUE THREAD

**Issue by ntf1974** [raphaelm/python-fints#168]
Since v4 of Library, param "product_id" must be defined on call of FinTS3PinTanClient.
Troubleshooting Script at https://python-fints.readthedocs.io/en/latest/trouble.html does not pay attention to this parameter.
However, users are advised not to modify the script.

Please add "product_id" Template to "client_args".

**Comment by raphaelm** [comment]
This is already fixed in the docs source but apparently the docs build process is broken, working on it
