### ISSUE TITLE
DKB no access to credit card accounts

### ISSUE THREAD

**Issue by raubtaube** [raphaelm/python-fints#19]
Hi there, thanks for the implementation. I was looking for scraping all the data from my bank account including credit card transactions. Am I missing something, or is this not implemented yet?

**Comment by simhnna** [comment]
This repo only gives you access using hbci. Sadly DKB doesn't include credit cards. There is another Python library that scrapes the info of their website. I've used it before and it worked well, I can't remember what it was though. It was also hosted on GitHub I guess...

**Comment by raphaelm** [comment]
In principle, credit cards can be accessible via HBCI, however if DKB just does not expose them, we can't do that ;) It might also be that DKB does expose them and the library does not find them – in this case, feel free to re-open the issue.

**Comment by daniel-tigges** [comment]
Are here any news regarding DKB and credit-card transactions? According to the f.get_information() statement the operation should be supported?

![image](https://github.com/user-attachments/assets/3c394108-4bab-448b-b560-9cb2f6fb64d2)
