### ISSUE TITLE
Extract account information from HIUPD

### ISSUE THREAD

**Issue by ChristianKuehnel** [raphaelm/python-fints#23]
First off: Cool library! :+1: 

Looking at my account and the [FinTS specification](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Formals_2017-10-06_final_version.pdf) , there is a field `HIUPD` containing some more information on the accounts. This could be used to give the accounts meaningful names, not just the account number.

Is there a reason why you did not parse this information?
Would you be interested in a pull request adding this feature?

**Comment by raphaelm** [comment]
To make this simple:

> Is there a reason why you did not parse this information?

No.

> Would you be interested in a pull request adding this feature?

Yes :)

**Comment by raphaelm** [comment]
Will be resolved after #34
