### ISSUE TITLE
Missing devaluation for Syntax character

### ISSUE THREAD

**Issue by RiRomain** [raphaelm/python-fints#35]
I was unable to connect to my broker HBCI server, and that was because my password contained the character **@**.

According to the standard, all **syntax character** need to be **devaluated (escaped) with character `?`**
For example the **password `1234@bcd` need to be replaced by `1234?@bcd`**

If not escaped with the character `?`, the bank parser evaluate the password as binary data and cannot process the message.

This behaviour is specified under Point **`H.1.3 Entwertung `** in [FinTS_3.0_Formats.pdf](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Formals_2017-10-06_final_version.pdf)

The **syntax character** are the following: **+ : ' ? @** (Point **`H.1.1 Syntaxzeichen `** in [FinTS_3.0_Formats.pdf](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Formals_2017-10-06_final_version.pdf))
  
  
They also include 2 example
Before:
`Taschengeld für Hans + Franz`
After:
`Taschengeld für Hans ?+ Franz`

Before
`Ist das so richtig??`
After
`Ist das so richtig????`

**Comment by raphaelm** [comment]
We have an escape method that apparently does not escape the ``@``: https://github.com/raphaelm/python-fints/blob/master/fints/utils.py#L21

**Comment by RiRomain** [comment]
Arf I'm really unlucky ^^ any reason for this method to not escape the '@'?

**Comment by raphaelm** [comment]
No, feel free to fix it :) When @henryk is done with his work in #34 and we're then also rewriting our protocol generation, it won't be neccessary any longer, but that might take some time.

**Comment by RiRomain** [comment]
Ok, I'll take a look, however I'm not sure how to discern Binary data from simple **@** character

**Comment by RiRomain** [comment]
https://github.com/raphaelm/python-fints/pull/37
