### ISSUE TITLE
HITANS segment version 1 is currently not implemented

### ISSUE THREAD

**Issue by elpatron68** [raphaelm/python-fints#36]
Hi,

thanks for this project.

I ran into a problem when I tried to get the balance of my _Postbank_ account:

```
def getbalance():
    blz = '12345600'
    account = 'foobar'
    pin = 'raboof'
    endpoint = 'https://hbci.postbank.de/banking/hbci.do'
    f = FinTS3PinTanClient(blz, account, pin, endpoint)
    konten = f.get_sepa_accounts()
    for konto in konten:
        print(konto.account + '\n')
        print(konto.getbalance())
```

DEBUG prints some lines of data, then the script exits in line 6 with `NotImplementedError: HITANS segment version 1 is currently not implemented`

Is there anything I can do about it?

Thanks,
Markus

**Comment by raphaelm** [comment]
Hi, thanks for reporting! This should be already fixed through #33, and I just now release fints 1.0.1 to address this.

**Comment by pluehne** [comment]
@raphaelm: Thanks for implementing these HITANS segments! I see that there is a commit mentioning the 1.0.1 release (832fcd0f4f56ccb27ffb8a0cc809168116031a16), but there’s no corresponding release tag for 1.0.1. Could you create such a `v1.0.1` release tag? This would really help for packaging this version of `python-fints` on platforms other than PyPi—for instance, the Arch Linux User Repository (AUR) :slightly_smiling_face:.

**Comment by raphaelm** [comment]
@pluehne Thanks for the heads up! Apparently, I created the tag but did not push it.

**Comment by pluehne** [comment]
@raphaelm: Thank you so much for pushing the tag :smile:!
