### ISSUE TITLE
Unable to connect to "Sparkasse" account.

### ISSUE THREAD

**Issue by brenkem** [raphaelm/python-fints#43]
I am not able to get my accounts. I checked the login twice and used the same on the bank website for verifkation. But in the first three times I get the same error and afterwards my account is locked.

```
import logging
from datetime import date
from fints.client import FinTS3PinTanClient
logging.basicConfig(level=logging.DEBUG)

f = FinTS3PinTanClient(
    'XXXXXXXX',  # Your bank's BLZ
    'YYYYYYYYYYY',  # Your login name
    'ZZZZZZZZZZZZZZZZZZZZZZZZZ',  # Your banking PIN
    'https://banking-sn4.s-fints-pt-sn.de/fints30'
)

konten = f.get_sepa_accounts()
```

I get the following output:
```
$ python3 get_statements.py 
INFO:fints.dialog:Initialize SYNC
DEBUG:fints.dialog:Sending SYNC: HNHBK:1:3+000000000367+300+0+1'HNVSK:998:3+PIN:1+998+1+1::0+1:20181122:184221+2:2:13:@8@00000000:5:1+280:XXXXXXXX:YYYYYYYYYYY:S:0:0+0'HNVSD:999:1+@204@HNSHK:2:4+PIN:1+999+8472868+1+1+1::0+1+1:20181122:184221+1:999:1+6:10:16+280:XXXXXXXX:YYYYYYYYYYY:S:0:0'HKIDN:3:2+280:XXXXXXXX+YYYYYYYYYYY+0+1'HKVVB:4:3+0+0+1+pyfints+0.1'HKSYN:5:3+0'HNSHA:6:2+8472868++***''HNHBS:7:1+1'
INFO:fints.dialog:Sending Message
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): banking-sn4.s-fints-pt-sn.de:443
DEBUG:urllib3.connectionpool:https://banking-sn4.s-fints-pt-sn.de:443 "POST /fints30 HTTP/1.1" 200 536
Traceback (most recent call last):
  File "get_statements.py", line 18, in <module>
    konten = f.get_sepa_accounts()
  File "/home/home/stahlstngel/Arbeitsfläche/script/account_checker/programming/python-fints/fints/client.py", line 44, in get_sepa_accounts
    dialog.sync()
  File "/home/home/stahlstngel/Arbeitsfläche/script/account_checker/programming/python-fints/fints/dialog.py", line 58, in sync
    resp = self.send(self._get_msg_sync())
  File "/home/home/stahlstngel/Arbeitsfläche/script/account_checker/programming/python-fints/fints/dialog.py", line 113, in send
    resp.get_summary_by_segment()
fints.dialog.FinTSDialogError: {'3920': 'Zugelassene Zwei-Schritt-Verfahren für den Benutzer.', '9010': 'Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet.', '9931': 'Anmeldename oder PIN ist falsch.', '9050': 'Die Nachricht enthält Fehler.', '9800': 'Dialog abgebrochen'}
```

The URL, the BLZ and the login name are right because my account gets locked. My PIN is also 100% the same. What else do I need to check?

Can someone tell me where the problem is?

**Comment by raphaelm** [comment]
Have you re-tried since release of version 2.0 of this library? There was a major rewrite, so maybe it works now. Feel free to reopen, if not.

**Comment by brenkem** [comment]
I can not reopen a issue if you closed it.

**Comment by raphaelm** [comment]
Where did you get Testaccount credentials from? ;)

**Comment by enniome** [comment]
If you search google for Sparkasse Testkonto you can find plenty. It seems that there are three test users for every Sparkasse:
- chipDEMO
- pushDEMO
- smsDEMO

The PIN is always 12345. I manage to log in into the Sparkasse E-Banking demo (i.e. https://www.sparkasse-bochum.de/de/home/login-online-banking/demo-online-banking-chiptan.html). All that's missing then is the BLZ and the Host which I have for a few. However, I cannot log in using python-fints.

**Comment by enniome** [comment]
It seems that it's not possible to connect to those demo accounts. I cross-checked with StarMoney and I'm getting the same errors.

**Comment by brenkem** [comment]
I also checked if my account is ready for FINTS by a android app and it was working fine (get account statement).

But I did not succeed by using this repo.

I there is anything else that I can check to support you…just let me know.

**Comment by enniome** [comment]
I now have access to a test account and everything seems to work just fine.

**Comment by brenkem** [comment]
I performed a 'git pull' (master) and tried it again. But got the same error as before (see [1]).
So you get it working with the test account? Did you also get it working with your private account?

[1]:
https://github.com/raphaelm/python-fints/issues/43#issuecomment-458713904

**Comment by raphaelm** [comment]
Closing this since the PSD branch is merged, see also here: https://github.com/raphaelm/python-fints/pull/95#issuecomment-568289618
