### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nafex** [raphaelm/python-fints#5]
Hi,
I'm trying to test your module but I always get the following error:

```
File "/usr/local/lib/python2.7/dist-packages/fints/client.py", line 24
    def _new_message(self, dialog: FinTSDialog, segments):
                                 ^
SyntaxError: invalid syntax
```

Can I use it with python 2.7?

**Comment by raphaelm** [comment]
No, Python 3 only, sorry.

**Comment by wvrzel** [comment]
Why is this module avilabeĺe via pip2, if it is only for python 3. It might be helpful to write this somewhere in the documentation.

**Comment by raphaelm** [comment]
I don't know of any way to tell pip whether a package is available for Python two or three, so that's why you find it with pip2 (except for the metadata tags, that are ignored).
