### ISSUE TITLE
fints-2.1.1 accountnumber vs account_number, etc.

### ISSUE THREAD

**Issue by drcicero** [raphaelm/python-fints#59]
Hi! Trying fints-2.1.1 from pypi, I got this error, calling `get_transactions`:

~~~
...
  File "/home/dave/.local/lib/python3.6/site-packages/fints/client.py", line 497, in get_transactions
    'HIKAZ'
  File "/home/dave/.local/lib/python3.6/site-packages/fints/client.py", line 436, in _fetch_with_touchdowns
    seg = segment_factory(touchdown)
  File "/home/dave/.local/lib/python3.6/site-packages/fints/client.py", line 491, in <lambda>
    account=hkkaz._fields['account'].type.from_sepa_account(account),
  File "/home/dave/.local/lib/python3.6/site-packages/fints/formals.py", line 506, in from_sepa_account
    account_number=acc.accountnumber,
AttributeError: 'KTZ1' object has no attribute 'accountnumber'
~~~

The problem is related to the following code portions of `formals.py`:

~~~python
class Account2 ...
     def from_sepa_account(cls, acc):
         return cls(
             account_number=acc.accountnumber,
             subaccount_number=acc.subaccount,
             country_identifier=BankIdentifier.COUNTRY_ALPHA_TO_NUMERIC[acc.bic[4:6]],
             bank_code=acc.blz,
         )

...

class Account3 ...
     def from_sepa_account(cls, acc):
         return cls(
             account_number=acc.accountnumber,
             subaccount_number=acc.subaccount,
             bank_identifier=BankIdentifier(
                 country_identifier=BankIdentifier.COUNTRY_ALPHA_TO_NUMERIC[acc.bic[4:6]],
                 bank_code=acc.blz
             )
         )
~~~

It seems to me that the `KTZ1` properties were refactored from `accountnumber` to `account_number` and from `blz` to `bank_identifier.bank_code`, but not in this place? So the following fix works for me:

~~~python
class Account2 ...
     def from_sepa_account(cls, acc):
         return cls(
             account_number=acc.account_number,
             subaccount_number=acc.subaccount_number,
             country_identifier=BankIdentifier.COUNTRY_ALPHA_TO_NUMERIC[acc.bic[4:6]],
             bank_code=acc.bank_identifier.bank_code,
         )

...

class Account3 ...
     def from_sepa_account(cls, acc):
         return cls(
             account_number=acc.account_number,
             subaccount_number=acc.subaccount_number,
             bank_identifier=acc.bank_identifier,
         )
~~~

I would guess `country_identifier` and `bank_code` in `Account2` could be refactored to `bank_identifier` to increase consistency, too? Maybe someone is doing that?

My issue here was written after only a short glance at the source code, and I have no idea about the complete picture :)

**Comment by raphaelm** [comment]
Hmm, no, that doesn't appear to be the issue, ``from_sepa_account`` shouldn't be passed a ``KTZ1`` instance, but a ``SEPAAccount`` instance, where it is still named ``accountnumber`` and ``blz``. Can you show us more of your ``get_transactions`` call and how you obtain the ``account`` parameter that you pass to it?

**Comment by drcicero** [comment]
Oops... Well I get the error by just doing:

~~~
cl = FinTS( ... )
_ = cl.get_sepa_accounts()
cl.get_transactions(cl.accounts[0])
~~~

... Ah! I just noticed, the return type of get_sepa_accounts is a list of `SEPAAccount`s, whereas cl.accounts is a list of `KTZ1`... I guess that was different in previous versions (either they had the same type or they their attributes had the same name). It seems like I am supposed to do:

~~~
cl = FinTS( ... )
accounts = cl.get_sepa_accounts()
cl.get_transactions(accounts[0])
~~~
