### ISSUE TITLE
can't connect to Targo (works with ruby_fints)

### ISSUE THREAD

**Issue by gingerlime** [raphaelm/python-fints#65]
Thanks so much for python-fints, it looks awesome. 🥇 

I'm having trouble using it with Targobank unfortunately. It works with Ing Diba for me without a problem, but not with Targo. I'm sure that I'm using the right login details, and it also works with [ruby_fints](https://github.com/playtestcloud/ruby_fints), which is odd for me, because it's just a ruby port of this library (right?).

Using python 3.7.0 inside pyenv on OSX

```
$ ipython
Python 3.7.0 (default, Jul  1 2018, 11:05:46)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from fints.client import FinTS3PinTanClient

In [2]: import getpass

In [3]: username = '***********'

In [4]: password = getpass.getpass()
Password:

In [5]: url = 'https://fints.targobank.de/travicretail_fints30pintanbroker/FinTs30PinTanHttpGate'

In [6]: blz = '30020900'

In [7]: f = FinTS3PinTanClient(blz, username, password, url)

In [8]: f.get_sepa_accounts()
---------------------------------------------------------------------------
FinTSConnectionError                      Traceback (most recent call last)
<ipython-input-8-89d709b83437> in <module>
----> 1 f.get_sepa_accounts()

~/.pyenv/versions/3.7.0/envs/fints/lib/python3.7/site-packages/fints/client.py in get_sepa_accounts(self)
    412         """
    413
--> 414         with self._get_dialog() as dialog:
    415             response = dialog.send(HKSPA1())
    416

~/.pyenv/versions/3.7.0/envs/fints/lib/python3.7/site-packages/fints/client.py in _get_dialog(self, lazy_init)
    252
    253         if not lazy_init:
--> 254             self._ensure_system_id()
    255
    256         return self._new_dialog(lazy_init=lazy_init)

~/.pyenv/versions/3.7.0/envs/fints/lib/python3.7/site-packages/fints/client.py in _ensure_system_id(self)
   1051         with self._get_dialog(lazy_init=True) as dialog:
   1052             response = dialog.init(
-> 1053                 HKSYN3(SynchronizationMode.NEW_SYSTEM_ID),
   1054             )
   1055

~/.pyenv/versions/3.7.0/envs/fints/lib/python3.7/site-packages/fints/dialog.py in init(self, *extra_segments)
     70             try:
     71                 self.open = True
---> 72                 retval = self.send(*segments, internal_send=True)
     73                 self.need_init = False
     74                 return retval

~/.pyenv/versions/3.7.0/envs/fints/lib/python3.7/site-packages/fints/dialog.py in send(self, *segments, **kwargs)
    112         self.next_message_number[message.DIRECTION] += 1
    113
--> 114         response = self.client.connection.send(message)
    115
    116         # assert response.segments[0].message_number == self.next_message_number[response.DIRECTION]

~/.pyenv/versions/3.7.0/envs/fints/lib/python3.7/site-packages/fints/connection.py in send(self, msg)
     28
     29         if r.status_code < 200 or r.status_code > 299:
---> 30             raise FinTSConnectionError('Bad status code {}'.format(r.status_code))
     31
     32         response = base64.b64decode(r.content.decode('iso-8859-1'))

FinTSConnectionError: Bad status code 403
```

Any clues / tips / suggestions?

P.S. Another odd thing that I should mention. When I use ruby_fints, I can list accounts, get balance, but when I try to get the transactions, they are empty for whichever date range I give. I'll report this on ruby_fints, but I just thought that it's odd. Maybe Targo isn't implementing things correctly? (just thought I'll mention it).

**Comment by raphaelm** [comment]
> I'm having trouble using it with Targobank unfortunately. It works with Ing Diba for me without a problem, but not with Targo. I'm sure that I'm using the right login details, and it also works with ruby_fints, which is odd for me, because it's just a ruby port of this library (right?).

ruby_fints appears to be a port of version 1.x of this library, but we have rewritten the whole protocol stack of this library in 2.x, so there are lots of differences.

Other than that, I don't have any great ideas here. Apparently, Targo rejects the request on a HTTP protocol level, not on a FinTS protocol level -- as if they were blocking your IP or the endpoint being wrong etc.

**Comment by henryk** [comment]
Hmm, where did you get the URL and is it the same used in ruby_fints?
I have an old copy of the hbci-zka.de list and that lists https://fints.targobank.de/travicretail_fints30pintanbroker/F as URL for BLZ 30020900.

**Comment by gingerlime** [comment]
See these lists, both are listing `https://fints.targobank.de/travicretail_fints30pintanbroker/FinTs30PinTanHttpGate` as the URL:

https://raw.githubusercontent.com/hbci4j/hbci4java/0072d401187a69a451eae1cbe928da3e2be6109f/src/main/resources/blz.properties

https://raw.githubusercontent.com/jhermsmeier/fints-institute-db/master/fints-institutes.json
