### ISSUE TITLE
Broken client context with IngDiba

### ISSUE THREAD

**Issue by Felixoid** [raphaelm/python-fints#66]
Hello. Thank you for the great module!

I couldn't connect to to IngDiba via `with` statement by some reason:
```
In [397]: with FinTS3PinTanClient(config['bank']['blz'], config['bank']['username'], config['bank']['password'], config['bank']['url']) as bank: 
     ...:     pass 
     ...:                                                                                                                                                                                     
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/lib/python3.7/site-packages/fints/dialog.py in init(self, *extra_segments)
     71                 self.open = True
---> 72                 retval = self.send(*segments, internal_send=True)
     73                 self.need_init = False

/usr/lib/python3.7/site-packages/fints/dialog.py in send(self, *segments, **kwargs)
    132 
--> 133         self.client.process_response_message(self, response, internal_send=internal_send)
    134 

/usr/lib/python3.7/site-packages/fints/client.py in process_response_message(self, dialog, message, internal_send)
    225 
--> 226                 self._process_response(dialog, segment, response)
    227 

/usr/lib/python3.7/site-packages/fints/client.py in _process_response(self, dialog, segment, response)
   1182                     # Fall back to onestep
-> 1183                     self.set_tan_mechanism('999')
   1184 

/usr/lib/python3.7/site-packages/fints/client.py in set_tan_mechanism(self, security_function)
   1225         if self._standing_dialog:
-> 1226             raise Exception("Cannot change TAN mechanism with a standing dialog")
   1227         self.selected_security_function = security_function

Exception: Cannot change TAN mechanism with a standing dialog

The above exception was the direct cause of the following exception:

FinTSDialogInitError                      Traceback (most recent call last)
<ipython-input-397-6d00de92b6dc> in <module>
----> 1 with FinTS3PinTanClient(config['bank']['blz'], config['bank']['username'], config['bank']['password'], config['bank']['url']) as bank:
      2     pass
      3 

/usr/lib/python3.7/site-packages/fints/client.py in __enter__(self)
    234             raise Exception("Cannot double __enter__() {}".format(self))
    235         self._standing_dialog = self._get_dialog()
--> 236         self._standing_dialog.__enter__()
    237 
    238     def __exit__(self, exc_type, exc_value, traceback):

/usr/lib/python3.7/site-packages/fints/dialog.py in __enter__(self)
     35         if self._context_count == 0:
     36             if not self.lazy_init:
---> 37                 self.init()
     38         self._context_count += 1
     39         return self

/usr/lib/python3.7/site-packages/fints/dialog.py in init(self, *extra_segments)
     78                     raise
     79                 else:
---> 80                     raise FinTSDialogInitError("Couldn't establish dialog with bank, Authentication data wrong?") from e
     81             finally:
     82                 self.lazy_init = False

FinTSDialogInitError: Couldn't establish dialog with bank, Authentication data wrong?
```

It works completely fine without context:
```
In [398]: bank = FinTS3PinTanClient(config['bank']['blz'], config['bank']['username'], config['bank']['password'], config['bank']['url'])

In [399]: bank.get_sepa_accounts()
Out[399]:
[SEPAAccount(iban='*******', bic='INGDDEFFXXX', accountnumber='*******', subaccount=None, blz='50010517'),
 SEPAAccount(iban='*******', bic='INGDDEFFXXX', accountnumber='*******', subaccount=None, blz='50010517')]
```
I use version 2.1.1

**Comment by Felixoid** [comment]
Do you need some additional info or something like that?

**Comment by michaelgreyskull** [comment]
Hi,
I want to confirm this! I am also having trouble logging in to ING Diba but the client context is established in another file.
The following code:
`f = FinTS3PinTanClient('50010517', '1234567890', 'onlinebankingPIN', 'https://fints.ing.de/fints/')
accounts = f.get_sepa_accounts()`
Throws this error:
`Traceback (most recent call last):
  File "test.py", line 213, in <module>
    accounts = f.get_sepa_accounts()
  File "path\to\fints\client.py", line 414, in get_sepa_accounts
    with self._get_dialog() as dialog:
  File "path\to\fints\client.py", line 254, in _get_dialog
    self._ensure_system_id()
  File "path\to\fints\client.py", line 1053, in _ensure_system_id
    HKSYN3(SynchronizationMode.NEW_SYSTEM_ID),
  File "path\to\fints\dialog.py", line 72, in init
    retval = self.send(*segments, internal_send=True)
  File "path\to\fints\dialog.py", line 133, in send
    self.client.process_response_message(self, response, internal_send=internal_send)
  File "path\to\fints\client.py", line 215, in process_response_message
    self._process_response(dialog, None, response)
  File "path\to\fints\client.py", line 1192, in _process_response
    raise FinTSClientPINError("Error during dialog initialization, PIN wrong?")
fints.exceptions.FinTSClientPINError: Error during dialog initialization, PIN wrong?`

For me it looks like the client.py is causing some trouble. What version are you using?

**Comment by Felixoid** [comment]
`2.1.1`

**Comment by michaelgreyskull** [comment]
any news here, Felixoid? Sorry that I am not a great help for this issue!

**Comment by Felixoid** [comment]
What news? There aren't any releases and reaction from developers here. What would be changed?

**Comment by UweZiegenhagen** [comment]
Hi @michaelgreyskull,

I tried it yesterday with Ing Diba, worked like a charm with 2.1.1. I am using the following:

f = FinTS3PinTanClient(
    '50010517',  # Your bank's BLZ
    '<accountnumer>', # Account Nummer
    '<password>', # HBCI PW
    'https://fints.ing-diba.de/fints/'  # endpoint, e.g.: https://hbci-pintan.gad.de/cgi-bin/hbciservlet
                            # for German banks, see http://www.hbci-zka.de/institute/institut_auswahl.htm
)

The difference to your code seems to be that I use ing-diba.de instead of ing.de

**Comment by Felixoid** [comment]
Hey, @UweZiegenhagen  
Thank you for your answer.

The problem described here is explicitly about executing not `f = FinTS3PinTanClient(`, but `with FinTS3PinTanClient(....) as f:`

**Comment by henryk** [comment]
@Felixoid Hmm, this is a problem in automatically selecting the correct two-step TAN mechanism when logging in. I thought I had found them all. (We need to specify a TAN mechanism with every message, including the message that asks for the list of available TAN mechanisms.)
Can you send the debug output that leads to it? You can remove personal data, I'm mostly interested in the message sequence and everything related to `security_function` and `code = '3920'`

```
import logging
from fints.client import FinTS3PinTanClient

logging.basicConfig(level=logging.DEBUG)

f = ...
```

**Comment by Felixoid** [comment]
Hello @henryk, sorry for a long silence.

I've done my best to remove personal data. Here is a debug info [fints-debug.txt](https://github.com/raphaelm/python-fints/files/3341842/fints-debug.txt)

I hope that's sufficient.

**Comment by raphaelm** [comment]
Here's HITANS:
```
fints.segments.auth.HITANS1(
	header = fints.formals.SegmentHeader('HITANS', 11, 1, 4), # Segmentkopf
	max_number_tasks = 1, # Maximale Anzahl Aufträge
	min_number_signatures = 1, # Anzahl Signaturen mindestens
	security_class = fints.formals.SecurityClass.NONE, # Sicherheitsklasse: Kein Sicherheitsdienst erforderlich
	parameter = fints.formals.ParameterTwostepTAN1(
			onestep_method_allowed = True,
			multiple_tasks_allowed = False,
			task_hash_algorithm = fints.formals.TaskHashAlgorithm.NONE, # Auftrags-Hashwertverfahren: Auftrags-Hashwert nicht unterstützt
			security_profile_bank_signature = '0',
			twostep_parameters = [
						fints.formals.TwoStepParameters1(
							security_function = '900', # Sicherheitsfunktion kodiert
							tan_process = '2', # TAN-Prozess
							tech_id = 'iTAN', # Technische Identifikation TAN-Verfahren
							name = 'iTAN', # Name des Zwei-Schritt-Verfahrens
							max_length_input = 6, # Maximale Länge des Eingabewertes im Zwei-Schritt-Verfahren
							allowed_format = fints.formals.AllowedFormat.NUMERIC, # Erlaubtes Format im Zwei-Schritt-Verfahren: numerisch
							text_return_value = 'Index', # Text zur Belegung des Rückgabewertes im Zwei-Schritt-Verfahren
							max_length_return_value = 3, # Maximale Länge des Rückgabewertes im Zwei-Schritt-Verfahren
							number_of_supported_lists = 1, # Anzahl unterstützter aktiver TAN-Listen
							multiple_tans_allowed = False, # Mehrfach-TAN erlaubt
							tan_time_delayed_allowed = False, # TAN zeitversetzt/dialogübergreifend erlaubt
						),
				],
		),
),
```

And here's ``3920``:

```
fints.formals.Response( # Rückmeldung
	code = '3920',
	reference_element = None,
	text = 'Zugelassene Ein- und Zwei-Schritt-Verfahren für den Benutzer',
	parameters = [
			'900',
		],
)
```

It looks to me as if we don't recognize this TAN method since we only look for HITANS in versions 2, 3, and 5:

```
IMPLEMENTED_HKTAN_VERSIONS = {
    2: HKTAN2,
    3: HKTAN3,
    5: HKTAN5,
}
```

However, IngDiba sends version 1. @henryk Is there a special reason you didn't implement version 1 and 4? I can surely add them, but I probably can't test them.

**Comment by henryk** [comment]
@raphaelm No special reason. Like you said, I started with the ones I found in the wild and which I could test (and my survey showed that there are only 5 banks which support version 1 only). 
One of the reasons I didn't do the other ones is that you may need to check the version or available attributes in other code besides just defining the segment type, see https://github.com/raphaelm/python-fints/pull/75/files#diff-e0468fc6cf96bcb942735a4f51a2fac4L1101 for an example

**Comment by raphaelm** [comment]
I see :) Let's see if I find the time to work on this blindly or if someone else (@Felixoid?) wants to contribute. If someone wants to contribute, here's how:

* Implement a class ``HKTAN1`` like ``HKTAN2``
* You can see how it needs to be different form ``HKTAN2`` by comparing the two versions in the [specification](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2018-02-23_final_version.pdf). Version 1 start on page 150, Version 2 is on page 154. Comparing these, you should see that from version 1 to 2, three fields were added and one removed. Therefore, you need to remove three fields and define a new one ("TAN-Zusatzinformationen").
* Add ``1: HKTAN1`` to the ``IMPLEMENTED_HKTAN_VERSIONS`` dictionary
* Run it and see what breaks. For example, as @henryk said, usages of the removed parameters might need to be checked.

**Comment by Felixoid** [comment]
Sorry for the long silence, it was a quite wild time. I'm not sure if I would be able to dig into it. Will return if find enough passion for Ing.de.

**Comment by raphaelm** [comment]
Let's close this for now – with PSD2 this no longer appears to be a problem since both we and ING now implement HKTAN6.
