### ISSUE TITLE
FinTS registration

### ISSUE THREAD

**Issue by jahir** [raphaelm/python-fints#83]
(Could be related to #72, not sure about it)

According to https://www.hbci-zka.de/register/prod_register.htm and https://www.hbci-zka.de/register/register_faq.htm (german only), FinTS access requires "product registration" and banks are supposed/required to deny access from non-registered clients on or shortly after 2019-08-01.

AFAICS, there is no support for this in python-fints, right? 
Are there plans to add this?
According to the Register FAQ it is possible (and intended) for register FinTS libraries. Products using these libraries are still required to get their own registration id, but the library should use its own id as a fallback. Do you know if anybody got such an registration id for open source software?

**Comment by raphaelm** [comment]
We have a registration for the product that we base on this, but we haven't registered the library in itself yet (as that is only to be used as a last resort, it's not the intended way of doing things). The registration process was easy and uncomplicated.

And yes, we should add support for specifying a registration number.

**Comment by raphaelm** [comment]
It's now possible to pass a custom ID: https://github.com/raphaelm/python-fints/commit/d691376414fd17aefe66fa260d074e4e198b01a8

I submitted a registration for a default ID for this kernel.

**Comment by raphaelm** [comment]
We got one! https://github.com/raphaelm/python-fints/commit/1ed83a801468947d1616775fb471a1810e1246b4

**Comment by jahir** [comment]
ok, I also applied for a registration.

Would you mind doing a new release?

**Comment by dr-duplo** [comment]
me, too.

**Comment by raphaelm** [comment]
Release 2.2.0 is there!

**Comment by jahir** [comment]
Nice, thanks!
Sparkasse will issue warnings (3078 and 3079) starting from 2019-07-22. I'm delaying my update until then...
