### ISSUE TITLE
netbank - Error 9370 (UPD oder BPD), get_balance OK, get_transactions EMPTY

### ISSUE THREAD

**Issue by TomBraider42** [raphaelm/python-fints#91]
Since 12.09.2019 (SCA) i get:
"9370 - Anzahl Signaturen für diesen Auftrag unzureichend laut UPD oder BPD."
In the Debug info system_id, bpd_version, upd_version all empty/zero.

Without `mode=FinTSClientMode.INTERACTIVE` i get a Message SCA ist necessary (9075).

With `mode=FinTSClientMode.INTERACTIVE` i get an empty list as get_transactions() response, no instance of NeedTANResponse. 

get_balance() works fine.

So how i can tell "netbank" to aks for an mTAN?
How can i "resynchronize" my data?
The examples in the Docu doesn't help.

**Comment by raphaelm** [comment]
Can you try the current version and script in #75?

**Comment by TomBraider42** [comment]
Same errors as https://github.com/raphaelm/python-fints/pull/95#issuecomment-536337639
Will wait for your new version tonight.

**Comment by TomBraider42** [comment]
Same Error, get_balance() works, get_transactions() is an empty list.
```
Dialog response: 9050 - Die Nachricht enthält Fehler.
Dialog response: 9370 - Anzahl Signaturen für diesen Auftrag unzureichend laut UPD oder BPD.
TAN Mediums not supported.
Transactions []
```
Because i logged in (and out) per Online Banking before, 2FA is not necessary.
The Android App Sparkasse shows the transactions without asking for a TAN.
So the bank backend seems to work.
I will send the debug-log per mail.
