### ISSUE TITLE
GLS Bank: Cannot get SEPA accounts

### ISSUE THREAD

**Issue by k-nut** [raphaelm/python-fints#92]
I have been using this library to execute read only operations on my bank (GLS eG) account. 

```python
    logging.basicConfig(level=logging.INFO)
    f = FinTS3PinTanClient(
        os.environ.get('CSA_ACCOUNT_BLZ'),
        os.environ.get('CSA_ACCOUNT_USERNAME'),
        os.environ.get('CSA_ACCOUNT_PASSWORD'),
        'https://hbci-pintan.gad.de/cgi-bin/hbciservlet',
        product_id=os.environ.get('CSA_HBCI_PRODUCT_ID', None)
    )
   accounts = f.get_sepa_accounts()
```
Unfortunately, since a couple of days (since the PSDS2 directive went into effect), I can no longer execute this code. It gets aborted with this output:
```
ERROR:fints.client:Dialog response: 9050 - Die Nachricht enthält Fehler.
ERROR:fints.client:Dialog response: 9075 - Starke Kundenauthentifizierung notwendig.
```

However, if I try to run the following code:
```
    try:
         accounts = f.get_sepa_accounts()
    except:
        pass
    print(f.get_tan_mechanisms())
```
I get the output `OrderedDict()`. 

This seems to me like my bank wants me to use 2 factor auth but also does not offer any form thereof over the FinTS interface. Am I missing something here?

PS: If I run just this snippet after the creation of the f object:

```python
    with f:
        print(f.get_tan_mechanisms())
```

I get this output:
```
Exception: Cannot change TAN mechanism with a standing dialog
```

**Comment by raphaelm** [comment]
See #72

**Comment by k-nut** [comment]
Ah sorry, I looked through the existing issues but somehow missed that one...
