### ISSUE TITLE
Sparkasse Köln Bonn: get_sepa_accounts fails

### ISSUE THREAD

**Issue by clemenswagner** [raphaelm/python-fints#94]
Hello,

I'm using fints to read transactions from a Sparkasse Köln-Bonn bank account. This works perfectly until Sept. 13, 2019, but fails after PSD2 migration at Saturday. I have a registered product id as specified in the documentation, and the Sparkasse also recognizes the product. But when I try to read the accounts with get_sepa_accounts I get the following errors:

Dialog response: 9050 - Die Nachricht enthält Fehler.
Dialog response: 9075 - Banking-Programm nicht PSD2-fähig, bitte aktualisieren.

How can I fix this issue?

Cheers
Clemens

**Comment by raphaelm** [comment]
Please wait for #72 to get resolved
